// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FootieData.Vsix
{
    static class Vsix
    {
        public const string Id = "28693b18-0c2c-4e86-adf2-adce836b749e";
        public const string Name = "Football";
        public const string Description = @"League tables. Results. Fixtures.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Greg Trevellick";
        public const string Tags = "Bundesliga, Championship, English, Football, Footie, Footy, League, Liga, Premier, Soccer, Sport, United, Liga";
    }
}
