// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FootieData.Vsix
{
    static class Vsix
    {
        public const string Id = "28693b18-0c2c-4e86-adf2-adce836b749e";
        public const string Name = "VS Sports Desk";
        public const string Description = @"A Visual Studio window displaying international soccer league tables, results and fixtures.";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Greg Trevellick";
        public const string Tags = "Beautiful game, Brasileiro, Bundesliga, Campeonato, Championship, Desk, English, Eredivisie, Football, Footie, Footy, League, Liga, Ligue, Premier, Primeira, Primera, Serie, Soccer, Sport";
    }
}
